make: 
	pdflatex --shell-escape -jobname=i2 main.tex
	pdflatex --shell-escape -jobname=i2 main.tex
	pdflatex --shell-escape -jobname=pauta-i2 pauta.tex
	pdflatex --shell-escape -jobname=pauta-i2 pauta.tex
