make: 
	pdflatex --shell-escape -jobname=i1 main.tex
	pdflatex --shell-escape -jobname=i1 main.tex
	pdflatex --shell-escape -jobname=pauta-i1 pauta.tex
	pdflatex --shell-escape -jobname=pauta-i1 pauta.tex
